import type { Run, ExecutionNode, Branch, PolicyDecisionEvent } from "@nemocognition/core";

export const demoRun: Run = {
  id: "run_demo_001",
  title: "Research Report Generation",
  userTask: "Create a research report from allowed documents and save it to ./output/report.md",
  status: "completed",
  createdAt: "2026-05-15T10:00:00Z",
  completedAt: "2026-05-15T10:05:30Z",
  rootBranchId: "branch_main",
};

export const demoBranches: Branch[] = [
  {
    id: "branch_main",
    runId: "run_demo_001",
    parentBranchId: null,
    forkNodeId: null,
    status: "failed",
    correctionSummary: null,
    createdAt: "2026-05-15T10:00:00Z",
  },
  {
    id: "branch_recovery_1",
    runId: "run_demo_001",
    parentBranchId: "branch_main",
    forkNodeId: "n04",
    status: "completed",
    correctionSummary: "Avoid reading from ./private/** — use only ./research/** files",
    createdAt: "2026-05-15T10:03:00Z",
  },
];

export const demoNodes: ExecutionNode[] = [
  {
    nodeId: "n01",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: null,
    checkpointId: "cp_start",
    type: "agent_message",
    status: "success",
    title: "Task received",
    summary: "NemoClaw agent received task: create research report from allowed documents.",
    startedAt: "2026-05-15T10:00:00Z",
    endedAt: "2026-05-15T10:00:01Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n02",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: "n01",
    checkpointId: null,
    type: "model_call",
    status: "success",
    title: "Planning: Nemotron generates research plan",
    summary: "Nemotron via NIM produced a plan: 1) Read paper notes 2) Synthesize findings 3) Write report to ./output/report.md",
    startedAt: "2026-05-15T10:00:01Z",
    endedAt: "2026-05-15T10:00:03Z",
    payloadRef: "payloads/run_demo_001/n02.json",
    validationRef: null,
  },
  {
    nodeId: "n03",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: "n02",
    checkpointId: "cp_pre_read",
    type: "policy_allow",
    status: "success",
    title: "File Read Allowed: ./research/paper-notes.md",
    summary: "OpenShell allowed read. Policy rule: allow_read: ./research/**",
    startedAt: "2026-05-15T10:00:03Z",
    endedAt: "2026-05-15T10:00:03Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n04",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: "n03",
    checkpointId: "cp_pre_private",
    type: "tool_call",
    status: "success",
    title: "cat ./research/paper-notes.md",
    summary: "Successfully read 2,400 words of research notes on neural scaling laws.",
    startedAt: "2026-05-15T10:00:04Z",
    endedAt: "2026-05-15T10:00:05Z",
    payloadRef: "payloads/run_demo_001/n04.json",
    validationRef: null,
  },
  {
    nodeId: "n05",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: "n04",
    checkpointId: null,
    type: "memory_update",
    status: "memory",
    title: "Memory: stored research findings",
    summary: "Agent memory updated with key findings from paper notes. Topics: scaling laws, compute efficiency, emergent capabilities.",
    startedAt: "2026-05-15T10:00:05Z",
    endedAt: "2026-05-15T10:00:05Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n06",
    runId: "run_demo_001",
    branchId: "branch_main",
    parentNodeId: "n05",
    checkpointId: "cp_before_denied",
    type: "policy_deny",
    status: "failure",
    title: "File Read Denied: ./private/api_keys.txt",
    summary: "OpenShell DENIED read. Policy rule: deny_read: ./private/**. Agent attempted to access private API keys for additional data sources.",
    startedAt: "2026-05-15T10:00:06Z",
    endedAt: "2026-05-15T10:00:06Z",
    payloadRef: "payloads/run_demo_001/n06.json",
    validationRef: "validations/run_demo_001/n06.json",
  },
  // Recovery branch
  {
    nodeId: "n07",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n04",
    checkpointId: "cp_pre_private",
    type: "branch_start",
    status: "branch",
    title: "Recovery branch: replan within policy",
    summary: "Forked from checkpoint cp_pre_private after File Read Denied at n06. Strategy: replan within policy.",
    startedAt: "2026-05-15T10:03:00Z",
    endedAt: "2026-05-15T10:03:00Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n08",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n07",
    checkpointId: null,
    type: "human_correction",
    status: "success",
    title: "Human correction applied",
    summary: "Use only ./research/** files for the report. Do not attempt to access ./private/**.",
    startedAt: "2026-05-15T10:03:01Z",
    endedAt: "2026-05-15T10:03:01Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n09",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n08",
    checkpointId: null,
    type: "model_call",
    status: "success",
    title: "Replanning: Nemotron generates corrected plan",
    summary: "Nemotron produced a corrected plan using only allowed resources. Skipping private data sources.",
    startedAt: "2026-05-15T10:03:02Z",
    endedAt: "2026-05-15T10:03:04Z",
    payloadRef: "payloads/run_demo_001/n09.json",
    validationRef: null,
  },
  {
    nodeId: "n10",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n09",
    checkpointId: null,
    type: "policy_allow",
    status: "success",
    title: "File Write Allowed: ./output/report.md",
    summary: "OpenShell allowed write. Policy rule: allow_write: ./output/**",
    startedAt: "2026-05-15T10:03:05Z",
    endedAt: "2026-05-15T10:03:05Z",
    payloadRef: null,
    validationRef: null,
  },
  {
    nodeId: "n11",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n10",
    checkpointId: null,
    type: "tool_call",
    status: "success",
    title: "Write report to ./output/report.md",
    summary: "Wrote 1,800-word research report on neural scaling laws to ./output/report.md.",
    startedAt: "2026-05-15T10:03:06Z",
    endedAt: "2026-05-15T10:03:08Z",
    payloadRef: "payloads/run_demo_001/n11.json",
    validationRef: null,
  },
  {
    nodeId: "n12",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    parentNodeId: "n11",
    checkpointId: null,
    type: "validation",
    status: "success",
    title: "Validation passed",
    summary: "Report exists at ./output/report.md, content length valid, no policy violations in recovery branch.",
    startedAt: "2026-05-15T10:03:09Z",
    endedAt: "2026-05-15T10:03:10Z",
    payloadRef: null,
    validationRef: "validations/run_demo_001/n12.json",
  },
];

export const demoPolicyEvents: PolicyDecisionEvent[] = [
  {
    eventId: "evt_allow_read",
    runId: "run_demo_001",
    branchId: "branch_main",
    nodeId: "n03",
    parentNodeId: "n02",
    checkpointId: "cp_pre_read",
    actionType: "file_read",
    decision: "allow",
    resource: "./research/paper-notes.md",
    normalizedResource: "./research/**",
    policyRuleId: "rule_allow_research",
    policyRuleText: "allow_read: ./research/**",
    policyPath: "files.allow_read[0]",
    reason: "File path matches allow_read pattern ./research/**",
    actor: "openshell",
    auditLogRef: "audit/run_demo_001/evt_allow_read.jsonl",
    timestamp: "2026-05-15T10:00:03Z",
    rawPayloadRef: "payloads/run_demo_001/evt_allow_read.json",
  },
  {
    eventId: "evt_deny_private",
    runId: "run_demo_001",
    branchId: "branch_main",
    nodeId: "n06",
    parentNodeId: "n05",
    checkpointId: "cp_before_denied",
    actionType: "file_read",
    decision: "deny",
    resource: "./private/api_keys.txt",
    normalizedResource: "./private/**",
    policyRuleId: "rule_deny_private",
    policyRuleText: "deny_read: ./private/**",
    policyPath: "files.deny_read[0]",
    reason: "File path matches deny_read pattern ./private/**",
    actor: "openshell",
    auditLogRef: "audit/run_demo_001/evt_deny_private.jsonl",
    timestamp: "2026-05-15T10:00:06Z",
    rawPayloadRef: "payloads/run_demo_001/evt_deny_private.json",
  },
  {
    eventId: "evt_allow_write",
    runId: "run_demo_001",
    branchId: "branch_recovery_1",
    nodeId: "n10",
    parentNodeId: "n09",
    checkpointId: null,
    actionType: "file_write",
    decision: "allow",
    resource: "./output/report.md",
    normalizedResource: "./output/**",
    policyRuleId: "rule_allow_output",
    policyRuleText: "allow_write: ./output/**",
    policyPath: "files.allow_write[0]",
    reason: "File path matches allow_write pattern ./output/**",
    actor: "openshell",
    auditLogRef: "audit/run_demo_001/evt_allow_write.jsonl",
    timestamp: "2026-05-15T10:03:05Z",
    rawPayloadRef: "payloads/run_demo_001/evt_allow_write.json",
  },
];

export const demoPolicy = `files:
  allow_read:
    - ./research/**
  deny_read:
    - ./private/**
  allow_write:
    - ./output/**
network:
  allow:
    - arxiv.org
    - docs.nvidia.com
  deny:
    - "*"
commands:
  allow:
    - cat
    - ls
    - python
  deny:
    - rm
    - curl`;
